/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9b5onU52HTv
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function ResearchUI() {
  return (
    (<section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container max-w-6xl px-4 md:px-6">
        <div className="space-y-6">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Research Portfolio 🔎</h2>
          <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
             <div
              className="group relative overflow-hidden rounded-lg shadow-lg transition-all duration-300 ease-in-out hover:shadow-xl hover:-translate-y-2">
              <a href="https://epoch.trading" className="absolute inset-0 z-10" target="_blank" rel="noopener">
                <span className="sr-only">View Project</span>
              </a>
              <img
                src="./Assets/abm-rn.png"
                alt="Research Project 2"
                width={600}
                height={400}
                className="h-64 w-full object-cover transition-all duration-300 ease-in-out group-hover:scale-105"
                style={{ aspectRatio: "600/400", objectFit: "cover" }} />
              <div className="space-y-2 bg-background p-4">
                <h3 className="text-xl font-semibold"> Agent Based Modeling of HFT (in progress)</h3>
                <p className="text-muted-foreground">
                  Disocverying how to create a ABM that can replicate the behavior of HFT firms.
                </p>
                {/* <div className="flex flex-wrap gap-2">
                  <span
                    className="rounded-full bg-primary px-3 py-1 text-xs font-medium text-primary-foreground">
                    Urban Planning
                  </span>
                  <span
                    className="rounded-full bg-primary px-3 py-1 text-xs font-medium text-primary-foreground">
                    Sustainability
                  </span>
                  <span
                    className="rounded-full bg-primary px-3 py-1 text-xs font-medium text-primary-foreground">
                    Community
                  </span>
                </div> */}
                <div className="text-sm text-muted-foreground absolute bottom-4">September 2024</div>
              </div>
            </div> 
           
            <div
              className="group relative overflow-hidden rounded-lg shadow-lg transition-all duration-300 ease-in-out hover:shadow-xl hover:-translate-y-2">
                <a href="https://innovate.iu.edu/innovates/index.html" className="absolute inset-0 z-10" target="_blank" rel="noopener noreferrer">
                <span className="sr-only">View Project</span>
              </a>
              <img
                src="./Assets/ma.png"
                alt="Research Project 1"
                width={600}
                height={400}
                className="h-64 w-full object-cover transition-all duration-300 ease-in-out group-hover:scale-105"
                style={{ aspectRatio: "600/400", objectFit: "cover" }} />
              <div className="space-y-2 bg-background p-4">
                
                <h3 className="text-xl font-semibold">Exploring how Founders Network (in progress)</h3>
                <p className="text-muted-foreground">
                An exploratory study on how foundes use networking skills to create a map of knowledge flow
                </p>
                {/* <div className="flex flex-wrap gap-2">
                  <span
                    className="rounded-full bg-primary px-3 py-1 text-xs font-medium text-primary-foreground">
                    Network Graphing
                  </span>
                  <span
                    className="rounded-full bg-primary px-3 py-1 text-xs font-medium text-primary-foreground">
                    Entrepreneurship
                  </span>
                  <span
                    className="rounded-full bg-primary px-3 py-1 text-xs font-medium text-primary-foreground">
                    Sociology
                  </span>
                </div> */}
                <div className="text-sm text-muted-foreground pt-5">June 2024</div>
              </div>
            </div>
     
            <div
              className="group relative overflow-hidden rounded-lg shadow-lg transition-all duration-300 ease-in-out hover:shadow-xl hover:-translate-y-2">
              <a href="https://eliserrano.substack.com/p/bloomingtons-homeless-situation-is" className="absolute inset-0 z-10" target="_blank" rel="noopener noreferrer">
                <span className="sr-only">View Project</span>
              </a>
              <img
                src="./Assets/S370.png"
                alt="Research Project 3"
                width={600}
                height={400}
                className="h-64 w-full object-cover transition-all duration-300 ease-in-out group-hover:scale-105"
                style={{ aspectRatio: "600/400", objectFit: "cover" }} />
              <div className="space-y-2 bg-background p-4">
                <h3 className="text-xl font-semibold">Sentiment Analysis of Unhoused Populations</h3>
                <p className="text-muted-foreground">
                  A comprehensive study on the sentiment of unhoused populations in Bloomington, Indiana.
                </p>
                {/* <div className="flex flex-wrap gap-2">
                  <span
                    className="rounded-full bg-primary px-3 py-1 text-xs font-medium text-primary-foreground">
                    Sentiment Analysis
                  </span>
                  <span
                    className="rounded-full bg-primary px-3 py-1 text-xs font-medium text-primary-foreground">
                    Sociology
                  </span>
                  <span
                    className="rounded-full bg-primary px-3 py-1 text-xs font-medium text-primary-foreground">
                    Ethnography
                  </span>
                  
                </div> */}
                <div className="text-sm text-muted-foreground pt-5">November 2023</div>
              </div>
            </div>

            <div
              className="group relative overflow-hidden rounded-lg shadow-lg transition-all duration-300 ease-in-out hover:shadow-xl hover:-translate-y-2">
              <a href="https://eliserrano.substack.com/p/bloomingtons-homeless-situation-is" className="absolute inset-0 z-10" target="_blank" rel="noopener noreferrer">
                <span className="sr-only">View Project</span>
              </a>
              <img
                src="./Assets/halo.jpg"
                alt="Research Project 3"
                width={600}
                height={400}
                className="h-64 w-full object-cover transition-all duration-300 ease-in-out group-hover:scale-105"
                style={{ aspectRatio: "600/400", objectFit: "cover" }} />
              <div className="space-y-2 bg-background p-4">
                <Link href="https://engineering.purdue.edu/HAB">
                <h3 className="text-xl font-semibold">Background Radiation and Microorganisms at Low Orbit</h3>
                <p className="text-muted-foreground">
                  Apart of Purdue's Project HALO. Lead software and telemetery on flight system that went into earth's high altitude.  

                </p>
                {/* <div className="flex flex-wrap gap-2">
                  <span
                    className="rounded-full bg-primary px-3 py-1 text-xs font-medium text-primary-foreground">
                    Sentiment Analysis
                  </span>
                  <span
                    className="rounded-full bg-primary px-3 py-1 text-xs font-medium text-primary-foreground">
                    Sociology
                  </span>
                  <span
                    className="rounded-full bg-primary px-3 py-1 text-xs font-medium text-primary-foreground">
                    Ethnography
                  </span>
                  
                </div> */}
                <div className="text-sm text-muted-foreground pt-5">August 2021</div>
                </Link>
              </div>
            </div>
            
          </div>
        </div>
      </div>
    </section>)
  );
}
